version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15.1
      - image: circleci/mongo:4.0.3
    
    working_directory: ~/repo

    steps:
      - checkout
      - run: "npm install"
      - run: "npm run build"
      - run: "npm run test"
